### ISSUE TITLE
RabbitMQ reporter

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin-reporter-java#58]
Pending the work described in openzipkin/zipkin#1614, we should implement a RabbitMQ reporter in this repository, which will help make supporting RabbitMQ in Java tracers easy.

We would need to pick a minimum version of the RabbitMQ Java client or shade it since users of this library could override the version we choose in their project.

**Comment by adriancole** [comment]
started a branch here which someone can pick-up

https://github.com/openzipkin/zipkin-reporter-java/tree/amqp-client
^^ named after the library, though seems the 5.x library is a much better library.. we could consider adding this instead of the 4.x one (and letting others ask for a <java 8 library)

requires zipkin 2.1 on the other side as that's the version that supports rabbitmq

**Comment by shakuzen** [comment]
I will make time to work on this tomorrow. though it looks like it's mostly done :-)

**Comment by shakuzen** [comment]
Implemented and released in version `2.1.0` of the reporter with #70
